### ISSUE TITLE
LogRhythm API Token handling (setting / storing / documentation)

### ISSUE THREAD

**Issue by GeneCupstid** [SmartResponse-Framework/SmartResponse.Framework#10]
Currently the value of `$SrfPreferences.LrDeployment.LrApiToken` isn't properly validated or reported to the user if missing.

**Comment by GeneCupstid** [comment]
Changes:

In `SrfPreferences`

- Add "instructions" array for context.
- Change the name of property `LrApiToken` to `LrApiCredential` to reduce confusion?  There are a LOT of references to this property, so it may not be the best idea to change its name.  If it was to happen, best to do it now rather than later, though.
- Add property `LrApiCredentialPath` to hold a path to a serialized `PSCredential` object with API Token in the password field.  This can be automatically imported when psm1 is run.
- Remove property `DefaultLrUserId` - it was never used for anything, though I had something in mind at some point.

Example of the new `LrDeployment` section if all of these changes are added:

```javascript
    "LrDeployment": {
        "Instructions": [
            "1. Update URLs to point to your Platform Manager / AI Engine server.",
            "3. If you'd like to use a saved token credential, include path to it in LrApiCredentialPath.",
            "2. DO NOT SET A VALUE FOR LrApiCredential - this will be set by the module if LrApiCredentialPath is set."
        ],
        "AdminApiBaseUrl": "https://server.comain.com:8501/lr-admin-api",
        "CaseApiBaseUrl": "https://server.comain.com:8501/lr-case-api",
        "AieApiUrl": "https://server.comain.com:8501/lr-drilldown-cache-api",
        "LrApiCredentialPath": "C:\\repos\\SmartResponse.Framework\\tests\\cred_LrApiToken.xml",
        "LrApiCredential": ""
    },
```

**Comment by GeneCupstid** [comment]
Idea:  `Set-LrApiToken` cmdlet - to walk user through process?

**Comment by GeneCupstid** [comment]
Created feature branch `10-LrApiToken` to begin work on this issue.

**Comment by Rusty-Shackleford** [comment]
This code is in dev now and will be merged in the next 24 hours.

**Comment by GeneCupstid** [comment]
This code is in dev now and will be merged in the next 24 hours.
